packages:
  - packages/*
  - sandbox/*

minimumReleaseAge: 4320

auditConfig:
  # HINT: Next.jsに関するpatchだが、SCのチェックでしか利用していないためignoreする
  ignoreGhsas:
    - GHSA-h25m-26qc-wcjf
    - GHSA-9g9p-9gw9-jx7f
    - GHSA-5f7q-jpqc-wp7h
minimumReleaseAgeExclude:
  # Renovate security update: webpack@5.104.1
  - webpack@5.104.1
