packages:
  - packages/*
  - sandbox/*

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  # Security update: esbuild@0.28.1
  - esbuild@0.28.1
  - '@esbuild/aix-ppc64@0.28.1'
  - '@esbuild/android-arm@0.28.1'
  - '@esbuild/android-arm64@0.28.1'
  - '@esbuild/android-x64@0.28.1'
  - '@esbuild/darwin-arm64@0.28.1'
  - '@esbuild/darwin-x64@0.28.1'
  - '@esbuild/freebsd-arm64@0.28.1'
  - '@esbuild/freebsd-x64@0.28.1'
  - '@esbuild/linux-arm@0.28.1'
  - '@esbuild/linux-arm64@0.28.1'
  - '@esbuild/linux-ia32@0.28.1'
  - '@esbuild/linux-loong64@0.28.1'
  - '@esbuild/linux-mips64el@0.28.1'
  - '@esbuild/linux-ppc64@0.28.1'
  - '@esbuild/linux-riscv64@0.28.1'
  - '@esbuild/linux-s390x@0.28.1'
  - '@esbuild/linux-x64@0.28.1'
  - '@esbuild/netbsd-arm64@0.28.1'
  - '@esbuild/netbsd-x64@0.28.1'
  - '@esbuild/openbsd-arm64@0.28.1'
  - '@esbuild/openbsd-x64@0.28.1'
  - '@esbuild/openharmony-arm64@0.28.1'
  - '@esbuild/sunos-x64@0.28.1'
  - '@esbuild/win32-arm64@0.28.1'
  - '@esbuild/win32-ia32@0.28.1'
  - '@esbuild/win32-x64@0.28.1'
allowBuilds:
  '@swc/core': true
  canvas: true
  esbuild: true
  sharp: true
overrides:
  postcss@<8.5.10: ^8.5.15
  esbuild@<=0.24.2: '>=0.28.1'
  esbuild@>=0.17.0 <0.28.1: '>=0.28.1'
  tar@<=7.5.15: '>=7.5.16'
  vite@>=7.0.0 <=7.3.4: '>=7.3.5'
  react-draggable: 4.5.0
  js-yaml@>=4.0.0 <=4.1.1: '>=4.1.2'
  '@babel/core@<=7.29.0': '>=7.29.1'
