import { storiesOf } from '@storybook/react'
import * as React from 'react'
import styled from 'styled-components'

import { Icon, Props } from './Icon'

const Wrapper = ({ children }: any) => <Container>{children}</Container>
const black = '#222'
const white = '#eee'
const icons: Array<Props['name']> = [
  'fa-address-book',
  'fa-address-card',
  'fa-angle-double-down',
  'fa-angle-double-left',
  'fa-angle-double-right',
  'fa-angle-down',
  'fa-angle-left',
  'fa-angle-right',
  'fa-angle-up',
  'fa-archive',
  'fa-arrow-circle-down',
  'fa-arrow-alt-circle-down',
  'fa-arrow-alt-circle-left',
  'fa-arrow-alt-circle-right',
  'fa-arrow-alt-circle-up',
  'fa-arrow-down',
  'fa-arrow-left',
  'fa-arrow-right',
  'fa-arrow-up',
  'fa-arrows-alt',
  'fa-arrows-alt-h',
  'fa-arrows-alt-v',
  'fa-asterisk',
  'fa-ban',
  'fa-bars',
  'fa-bell',
  'fa-bell-slash',
  'fa-birthday-cake',
  'fa-bolt',
  'fa-book',
  'fa-book-open',
  'fa-bookmark',
  'fa-box',
  'fa-box-open',
  'fa-boxes',
  'fa-briefcase',
  'fa-building',
  'fa-bullhorn',
  'fa-bus',
  'fa-bus-alt',
  'fa-business-time',
  'fa-calculator',
  'fa-calendar',
  'fa-calendar-alt',
  'fa-calendar-check',
  'fa-calendar-day',
  'fa-calendar-minus',
  'fa-calendar-plus',
  'fa-calendar-times',
  'fa-calendar-week',
  'fa-camera',
  'fa-car',
  'fa-car-alt',
  'fa-car-side',
  'fa-caret-down',
  'fa-caret-left',
  'fa-caret-right',
  'fa-caret-square-down',
  'fa-caret-square-left',
  'fa-caret-square-right',
  'fa-caret-square-up',
  'fa-caret-up',
  'fa-chart-area',
  'fa-chart-bar',
  'fa-chart-line',
  'fa-chart-pie',
  'fa-check',
  'fa-check-circle',
  'fa-check-square',
  'fa-chevron-circle-down',
  'fa-chevron-circle-left',
  'fa-chevron-circle-right',
  'fa-chevron-circle-up',
  'fa-chevron-down',
  'fa-chevron-left',
  'fa-chevron-right',
  'fa-chevron-up',
  'fa-circle',
  'fa-clipboard',
  'fa-clipboard-check',
  'fa-clipboard-list',
  'fa-clock',
  'fa-clone',
  'fa-cloud',
  'fa-cloud-download-alt',
  'fa-cloud-upload-alt',
  'fa-code',
  'fa-cog',
  'fa-cogs',
  'fa-coins',
  'fa-columns',
  'fa-comment',
  'fa-comment-alt',
  'fa-comment-dots',
  'fa-comment-slash',
  'fa-comments',
  'fa-compress',
  'fa-copy',
  'fa-credit-card',
  'fa-cube',
  'fa-cubes',
  'fa-database',
  'fa-door-closed',
  'fa-door-open',
  'fa-edit',
  'fa-ellipsis-h',
  'fa-ellipsis-v',
  'fa-envelope',
  'fa-envelope-open',
  'fa-envelope-open-text',
  'fa-exchange-alt',
  'fa-exclamation',
  'fa-exclamation-circle',
  'fa-exclamation-triangle',
  'fa-expand',
  'fa-expand-arrows-alt',
  'fa-external-link-alt',
  'fa-eye',
  'fa-eye-slash',
  'fa-file',
  'fa-file-alt',
  'fa-file-archive',
  'fa-file-download',
  'fa-file-export',
  'fa-file-import',
  'fa-file-upload',
  'fa-filter',
  'fa-flag',
  'fa-folder',
  'fa-folder-minus',
  'fa-folder-open',
  'fa-folder-plus',
  'fa-font',
  'fa-forward',
  'fa-gift',
  'fa-globe',
  'fa-graduation-cap',
  'fa-grip-horizontal',
  'fa-grip-lines',
  'fa-grip-lines-vertical',
  'fa-grip-vertical',
  'fa-hand-paper',
  'fa-hand-point-down',
  'fa-hand-point-left',
  'fa-hand-point-right',
  'fa-hand-point-up',
  'fa-hands',
  'fa-handshake',
  'fa-heart',
  'fa-history',
  'fa-home',
  'fa-hospital',
  'fa-hospital-alt',
  'fa-hourglass',
  'fa-hourglass-end',
  'fa-hourglass-half',
  'fa-hourglass-start',
  'fa-id-badge',
  'fa-id-card',
  'fa-id-card-alt',
  'fa-image',
  'fa-images',
  'fa-inbox',
  'fa-info',
  'fa-info-circle',
  'fa-key',
  'fa-keyboard',
  'fa-lightbulb',
  'fa-link',
  'fa-list',
  'fa-list-alt',
  'fa-list-ol',
  'fa-list-ul',
  'fa-lock',
  'fa-lock-open',
  'fa-long-arrow-alt-down',
  'fa-long-arrow-alt-left',
  'fa-long-arrow-alt-right',
  'fa-long-arrow-alt-up',
  'fa-medkit',
  'fa-minus',
  'fa-minus-circle',
  'fa-minus-square',
  'fa-mobile',
  'fa-mobile-alt',
  'fa-money-bill',
  'fa-money-bill-alt',
  'fa-money-bill-wave',
  'fa-money-bill-wave-alt',
  'fa-money-check',
  'fa-money-check-alt',
  'fa-paper-plane',
  'fa-paperclip',
  'fa-paste',
  'fa-pen',
  'fa-pencil-alt',
  'fa-phone',
  'fa-phone-slash',
  'fa-piggy-bank',
  'fa-plane',
  'fa-play',
  'fa-play-circle',
  'fa-plus',
  'fa-plus-circle',
  'fa-plus-square',
  'fa-poll',
  'fa-poll-h',
  'fa-portrait',
  'fa-power-off',
  'fa-print',
  'fa-qrcode',
  'fa-question',
  'fa-question-circle',
  'fa-random',
  'fa-receipt',
  'fa-redo',
  'fa-redo-alt',
  'fa-reg-dot-circle',
  'fa-reply',
  'fa-reply-all',
  'fa-rocket',
  'fa-save',
  'fa-search',
  'fa-search-minus',
  'fa-search-plus',
  'fa-share',
  'fa-share-alt',
  'fa-share-square',
  'fa-shield-alt',
  'fa-shopping-bag',
  'fa-shopping-basket',
  'fa-shopping-cart',
  'fa-sign-in-alt',
  'fa-sign-out-alt',
  'fa-sliders-h',
  'fa-sort',
  'fa-sort-alpha-down',
  'fa-sort-alpha-up',
  'fa-sort-amount-down',
  'fa-sort-amount-up',
  'fa-sort-down',
  'fa-sort-numeric-down',
  'fa-sort-numeric-up',
  'fa-sort-up',
  'fa-star',
  'fa-step-backward',
  'fa-step-forward',
  'fa-sticky-note',
  'fa-stop',
  'fa-stop-circle',
  'fa-stream',
  'fa-subway',
  'fa-sync',
  'fa-sync-alt',
  'fa-table',
  'fa-tablet',
  'fa-tablet-alt',
  'fa-tachometer-alt',
  'fa-tag',
  'fa-tags',
  'fa-task',
  'fa-taxi',
  'fa-th',
  'fa-th-large',
  'fa-th-list',
  'fa-times',
  'fa-times-circle',
  'fa-toolbox',
  'fa-tools',
  'fa-trash',
  'fa-trash-alt',
  'fa-trash-restore',
  'fa-trash-restore-alt',
  'fa-undo',
  'fa-undo-alt',
  'fa-unlink',
  'fa-unlock',
  'fa-unlock-alt',
  'fa-user',
  'fa-user-alt',
  'fa-user-alt-slash',
  'fa-user-check',
  'fa-user-circle',
  'fa-user-cog',
  'fa-user-edit',
  'fa-user-minus',
  'fa-user-plus',
  'fa-user-slash',
  'fa-users',
  'fa-users-cog',
  'fa-video',
  'fa-video-slash',
  'fa-volume-down',
  'fa-volume-mute',
  'fa-volume-off',
  'fa-volume-up',
  'fa-wallet',
  'fa-window-close',
  'fa-window-maximize',
  'fa-window-minimize',
  'fa-window-restore',
  'fa-wrench',
  'fa-yen-sign',
]

const getIconList = (bg: string, color?: string) =>
  icons.map((name) => (
    <IconWrap key={`${color}-${name}`} bg={bg}>
      <Icon name={name} color={color} />
      <IconName color={color}>{name}</IconName>
    </IconWrap>
  ))

storiesOf('Icon', module)
  .add('white', () => <Wrapper>{getIconList(black, white)}</Wrapper>)
  .add('black', () => <Wrapper>{getIconList(white, black)}</Wrapper>)
  .add('default', () => <Wrapper>{getIconList(white)}</Wrapper>)

const Container = styled.div`
  display: flex;
  justify-content: start;
  align-items: center;
  flex-wrap: wrap;
`
const IconWrap: any = styled.div`
  margin: 10px;
  padding: 10px;
  background-color: ${({ bg }: any) => bg};
  text-align: center;
`
const IconName = styled.p`
  margin-top: 10px;
  color: ${({ color }: any) => color};
  font-size: 14px;
`
