#!/bin/bash

{
  cat <<EOF
// Code generated by generate.sh; DO NOT EDIT
// FIXME: react-pdfで要求されているCSSをsmarthr-uiからexportする方法がないので、暫定的にコピーしてstyleタグで配信している
export const ReactPDFStyle = () => (
  <style>
    {\`
EOF
  cat $(readlink -f "../../../node_modules/react-pdf/dist/esm/Page/TextLayer.css")
  cat $(readlink -f "../../../node_modules/react-pdf/dist/esm/Page/AnnotationLayer.css")
  cat <<EOF
    \`}
  </style>
)
EOF
} > "./generatedReactPDFStyle.tsx"
