# 日本語辞書を翻訳ツール(Crowdin)にアップロード
name: "i18n: Upload Japanese dictionary to Crowdin"

on:
  schedule:
    - cron: "0 8 * * MON"
      timezone: Asia/Tokyo
  workflow_dispatch:
    inputs:
      github_branch:
        description: アップするブランチ名（Crowdinブランチ名としても使用される）
        required: false
        default: ""
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.github_branch || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  crowdin:
    name: "Upload Japanese dictionary to Crowdin"
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: ${{ inputs.github_branch || github.ref_name }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ env.TARGET_BRANCH }}
          persist-credentials: false
      - name: Push ja-JP source to Crowdin
        uses: crowdin/github-action@8868a33591d21088edfc398968173a3b98d51706 # v2.16.2
        with:
          config: crowdin.yml
          upload_sources: true
          upload_translations: false
          download_translations: false
          crowdin_branch_name: ${{ env.TARGET_BRANCH }}
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PUSH_PULL_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_BASE_URL: ${{ secrets.CROWDIN_BASE_URL }}
