name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  pull_request_review:
    types: [submitted]

jobs:
  conventional_commits:
    if: ${{ (((github.event_name != 'pull_request_review') && !(startsWith(github.event.pull_request.head.ref, 'merge-release-'))) || (github.event_name == 'pull_request_review') && (startsWith(github.event.pull_request.head.ref, 'merge-release-'))) }}
    runs-on: ubuntu-latest
    steps:
      - name: check title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          regex="^(feat|fix|docs|chore|style|refactor|perf|test)(\([^\)]+\))?!?:[[:space:]].+"
          if [[ "$PR_TITLE" =~ $regex ]]; then
              echo OK
          else
              echo "::error::Pull Request のタイトルが Conventional Commits 形式にマッチしません"
              exit 1
          fi
