name: Typo Checker
on: [pull_request]

jobs:
  run:
    name: Typo Checker
    runs-on: ubuntu-latest
    steps:
    - uses: kufu/safe-chain-orb@90f4f6b5e801be1257a4e3ac1756f2136d023ef6 # main
    - uses: actions/checkout@v4
    - name: Use custom config file
      uses: crate-ci/typos@master
      with:
        config: ./.typos.toml
