name: Typo Checker
on: [pull_request]

jobs:
  run:
    name: Typo Checker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Use custom config file
      uses: crate-ci/typos@master
      with:
        config: ./.typos.toml
